/**
 * Client-side brand data reader.
 * Reads from NEXT_PUBLIC_BRAND_ env vars (generated by scripts/sync-env.js).
 * Safe to import in "use client" components.
 */

function env(key: string, fallback: string = ""): string {
  return process.env[key] || fallback;
}

function envJson<T>(key: string, fallback: T): T {
  try {
    const val = process.env[key];
    return val ? JSON.parse(val) : fallback;
  } catch {
    return fallback;
  }
}

export function getBrand() {
  return {
    name: env("NEXT_PUBLIC_BRAND_NAME", "Apex Field Services"),
    phone: env("NEXT_PUBLIC_BRAND_PHONE", "(555) 123-4567"),
    tagline: env("NEXT_PUBLIC_BRAND_TAGLINE", "Fast. Reliable. Guaranteed."),
    area: env("NEXT_PUBLIC_BRAND_AREA", "Local Area"),
    years: parseInt(env("NEXT_PUBLIC_BRAND_YEARS", "10")),
    responseMin: parseInt(env("NEXT_PUBLIC_BRAND_RESPONSE_MIN", "15")),
    color: env("NEXT_PUBLIC_BRAND_COLOR", "#f59e0b"),
  };
}

export type ServiceItem = { label: string; icon: string };
export type ReviewItem = { name: string; rating: number; text: string; date: string; service: string };
export type FaqItem = { question: string; answer: string };
export type TrustBadge = { label: string; icon: string };

export function getServices(): string[] {
  return envJson<string[]>("NEXT_PUBLIC_BRAND_SERVICES", []);
}

export function getReviews(): ReviewItem[] {
  return envJson<ReviewItem[]>("NEXT_PUBLIC_BRAND_REVIEWS", []);
}

export function getFaq(): FaqItem[] {
  return envJson<FaqItem[]>("NEXT_PUBLIC_BRAND_FAQ", []);
}

export function getTrustBadges(): TrustBadge[] {
  return envJson<TrustBadge[]>("NEXT_PUBLIC_BRAND_TRUST_BADGES", []);
}
